INSERT INTO countrys (name) VALUES ('United States');
INSERT INTO countrys (name) VALUES ('Canada');
INSERT INTO countrys (name) VALUES ('Mexico');
INSERT INTO countrys (name) VALUES ('Brazil');
INSERT INTO countrys (name) VALUES ('Argentina');
INSERT INTO countrys (name) VALUES ('United Kingdom');
INSERT INTO countrys (name) VALUES ('France');
INSERT INTO countrys (name) VALUES ('Germany');
INSERT INTO countrys (name) VALUES ('Italy');
INSERT INTO countrys (name) VALUES ('Spain');
INSERT INTO countrys (name) VALUES ('Portugal');
INSERT INTO countrys (name) VALUES ('Netherlands');
INSERT INTO countrys (name) VALUES ('Belgium');
INSERT INTO countrys (name) VALUES ('Switzerland');
INSERT INTO countrys (name) VALUES ('Sweden');
INSERT INTO countrys (name) VALUES ('Norway');
INSERT INTO countrys (name) VALUES ('Denmark');
INSERT INTO countrys (name) VALUES ('Finland');
INSERT INTO countrys (name) VALUES ('Russia');
INSERT INTO countrys (name) VALUES ('China');
INSERT INTO countrys (name) VALUES ('Japan');
INSERT INTO countrys (name) VALUES ('South Korea');
INSERT INTO countrys (name) VALUES ('India');
INSERT INTO countrys (name) VALUES ('Australia');
INSERT INTO countrys (name) VALUES ('New Zealand');
INSERT INTO countrys (name) VALUES ('South Africa');
INSERT INTO countrys (name) VALUES ('Egypt');
INSERT INTO countrys (name) VALUES ('Nigeria');
INSERT INTO countrys (name) VALUES ('Kenya');
INSERT INTO countrys (name) VALUES ('Morocco');
INSERT INTO countrys (name) VALUES ('Turkey');
INSERT INTO countrys (name) VALUES ('Saudi Arabia');
INSERT INTO countrys (name) VALUES ('United Arab Emirates');
INSERT INTO countrys (name) VALUES ('Iran');
INSERT INTO countrys (name) VALUES ('Israel');
INSERT INTO countrys (name) VALUES ('Jordan');
INSERT INTO countrys (name) VALUES ('Lebanon');
INSERT INTO countrys (name) VALUES ('Iraq');
INSERT INTO countrys (name) VALUES ('Syria');
INSERT INTO countrys (name) VALUES ('Pakistan');
INSERT INTO countrys (name) VALUES ('Bangladesh');
INSERT INTO countrys (name) VALUES ('Sri Lanka');
INSERT INTO countrys (name) VALUES ('Nepal');
INSERT INTO countrys (name) VALUES ('Bhutan');
INSERT INTO countrys (name) VALUES ('Maldives');
INSERT INTO countrys (name) VALUES ('Singapore');
INSERT INTO countrys (name) VALUES ('Malaysia');
INSERT INTO countrys (name) VALUES ('Thailand');
INSERT INTO countrys (name) VALUES ('Vietnam');
INSERT INTO countrys (name) VALUES ('Philippines');
INSERT INTO countrys (name) VALUES ('Indonesia');
INSERT INTO countrys (name) VALUES ('Myanmar');
INSERT INTO countrys (name) VALUES ('Cambodia');
INSERT INTO countrys (name) VALUES ('Laos');
INSERT INTO countrys (name) VALUES ('Brunei');
INSERT INTO countrys (name) VALUES ('Timor-Leste');
INSERT INTO countrys (name) VALUES ('Papua New Guinea');
INSERT INTO countrys (name) VALUES ('Fiji');
INSERT INTO countrys (name) VALUES ('Solomon Islands');
INSERT INTO countrys (name) VALUES ('Vanuatu');
INSERT INTO countrys (name) VALUES ('Kiribati');
INSERT INTO countrys (name) VALUES ('Tuvalu');
INSERT INTO countrys (name) VALUES ('Nauru');
INSERT INTO countrys (name) VALUES ('Palau');
INSERT INTO countrys (name) VALUES ('Marshall Islands');
INSERT INTO countrys (name) VALUES ('Micronesia');
