INSERT INTO sports (name, description) VALUES ('Salto com Vara', 'Consiste em passar sobre um bastão usando uma vara para alavancar-se.');
INSERT INTO sports (name, description) VALUES ('Futebol', 'Esporte coletivo onde duas equipes de 11 jogadores tentam marcar gols na meta adversária.');
INSERT INTO sports (name, description) VALUES ('Basquete', 'Esporte coletivo onde duas equipes de 5 jogadores tentam fazer a bola entrar na cesta do time adversário.');
INSERT INTO sports (name, description) VALUES ('Natação', 'Esporte aquático onde os atletas competem em diferentes estilos de nado em piscina.');
INSERT INTO sports (name, description) VALUES ('Vôlei', 'Esporte coletivo jogado por duas equipes de seis jogadores que tentam fazer a bola tocar o chão no campo adversário.');
INSERT INTO sports (name, description) VALUES ('Tênis', 'Esporte onde jogadores usam raquetes para bater uma bola sobre uma rede para o lado adversário.');
INSERT INTO sports (name, description) VALUES ('Atletismo', 'Conjunto de esportes que inclui corridas, saltos e arremessos, geralmente realizados em pistas ou campos.');
INSERT INTO sports (name, description) VALUES ('Ciclismo', 'Esporte que envolve o uso de bicicletas para competições em estrada, pista ou montanha.');
INSERT INTO sports (name, description) VALUES ('Judô', 'Arte marcial que se concentra em técnicas de projeção e imobilização do adversário no solo.');
INSERT INTO sports (name, description) VALUES ('Karate', 'Arte marcial que utiliza golpes com as mãos e os pés para defesa e ataque.');
INSERT INTO sports (name, description) VALUES ('Boxe', 'Esporte de combate onde os atletas lutam usando apenas os punhos, com o objetivo de nocautear o adversário.');
INSERT INTO sports (name, description) VALUES ('Esgrima', 'Esporte de combate onde os atletas usam espadas para tocar o adversário e marcar pontos.');
INSERT INTO sports (name, description) VALUES ('Handebol', 'Esporte coletivo onde duas equipes de sete jogadores tentam marcar gols arremessando uma bola nas metas adversárias.');
INSERT INTO sports (name, description) VALUES ('Rugby', 'Esporte coletivo que combina elementos de futebol e de contato, jogado com uma bola oval.');
INSERT INTO sports (name, description) VALUES ('Taekwondo', 'Arte marcial coreana focada em chutes e técnicas de defesa e ataque com os pés.');
INSERT INTO sports (name, description) VALUES ('Golf', 'Esporte onde os jogadores usam clavas para acertar uma bola em buracos no menor número de tacadas possível.');
INSERT INTO sports (name, description) VALUES ('Patinação Artística', 'Esporte onde os atletas realizam performances artísticas sobre patins no gelo.');
INSERT INTO sports (name, description) VALUES ('Esqui', 'Esporte de inverno onde os atletas deslizam sobre a neve usando esquis.');
INSERT INTO sports (name, description) VALUES ('Snowboard', 'Esporte de inverno em que os atletas deslizam sobre a neve em uma prancha única.');
INSERT INTO sports (name, description) VALUES ('Ski Jumping', 'Esporte de esqui onde os atletas descem por uma rampa e tentam realizar o salto mais longo possível.');
INSERT INTO sports (name, description) VALUES ('Luta Livre', 'Esporte de combate onde os atletas utilizam técnicas de agarramento e controle para vencer o adversário.');
INSERT INTO sports (name, description) VALUES ('Pentatlo Moderno', 'Esporte que combina esgrima, natação, corrida, hipismo e tiro.');
INSERT INTO sports (name, description) VALUES ('Arco e Flecha', 'Esporte onde os atletas usam arcos para disparar flechas em um alvo.');
INSERT INTO sports (name, description) VALUES ('Triatlo', 'Esporte que combina natação, ciclismo e corrida em uma única competição.');
INSERT INTO sports (name, description) VALUES ('Handebol de Praia', 'Versão do handebol jogada na areia, com equipes de quatro jogadores.');
INSERT INTO sports (name, description) VALUES ('Futsal', 'Versão do futebol jogada em campo reduzido e com uma bola menor e mais pesada.');
INSERT INTO sports (name, description) VALUES ('Skate', 'Esporte de rua que envolve manobras e habilidades realizadas sobre um skate.');
INSERT INTO sports (name, description) VALUES ('Surf', 'Esporte aquático onde os atletas usam pranchas para surfar ondas no mar.');
INSERT INTO sports (name, description) VALUES ('Kitesurf', 'Esporte aquático que combina surf com a utilização de uma pipa para propulsão.');
